Fixed TypeError: contactGateway is not a function
Remote Objects proxy object was being used incorrectly throughout the
app. I added an actual factory method that returns the proxy object for
the service and updated the instances where it is used.